// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byuegoiwjbbreaxioesw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dWVnb2l3amJicmVheGlvZXN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Nzk0NTQsImV4cCI6MjA2NjU1NTQ1NH0.H0YoLbvKm8W4GDDVXTVG921CjqRD-nIqosLDTjNqtbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);